import type { Locale } from "./i18n";
import { site } from "./site";

export const chrome = {
  en: {
    nav: {
      home: "Home",
      services: "Services",
      areas: "Areas",
      guides: "Guides",
      faq: "FAQ",
      about: "About",
      contact: "Contact",
      book: "Book",
      bookVisit: "Book a visit",
      call: "Call",
      menu: "Menu",
      close: "Close",
      mainNav: "Main",
      mobileNav: "Mobile",
      language: "Language",
    },
    footer: {
      blurb:
        "Independent marine diagnostics and repair. Clear findings, free estimates, dockside when access allows.",
      services: "Services",
      areas: "Areas",
      book: "Book",
      bookVisit: "Book a visit",
      estimate: "Get a free estimate",
      reviews: "Reviews",
      privacy: "Privacy",
      terms: "Terms",
      tag: "Diagnose first · free estimates",
    },
    cta: {
      eyebrow: "Book this week",
      title: "Book a visit — we confirm by phone",
      body: `Submit a request or call ${site.phone}. We confirm during ${site.hours}. Diagnose first. Free estimates on recommended work.`,
      reviews: "Reviews on",
      book: "Book a visit",
      estimate: "Get a free estimate",
      call: `Call ${site.phone}`,
    },
    mobileCta: {
      call: "Call",
      estimate: "Estimate",
      book: "Book a visit",
    },
    serviceCard: {
      details: "Service details →",
    },
    servicePage: {
      eyebrow: (duration?: string) => (duration ? `Service · ${duration}` : "Service"),
      crumbHome: "Home",
      crumbServices: "Services",
      areaLine: "Fort Lauderdale · South Florida · Dockside first",
      book: "Book a visit",
      estimate: "Get a free estimate",
      call: `Call ${site.phone}`,
      quickLabel: "Quick answer · on the water",
      quickQuestion: (title: string) => `What is ${title.toLowerCase()}?`,
      aboutEyebrow: "On the dock",
      aboutTitle: (title: string) => `About ${title.toLowerCase()} at Doctor Yachts`,
      symptomsEyebrow: "Symptoms",
      symptomsTitle: "Common symptoms we see",
      symptomsLead: "If any of these sound familiar, this service is usually the right place to start:",
      scopeEyebrow: "Scope",
      scopeTitle: "What's typically included",
      detailsEyebrow: "Details",
      inspectEyebrow: "Inspection",
      inspectTitle: "What we check on a visit",
      inspectLead: (title: string) =>
        `Scope always follows your symptom and vessel, but a typical ${title.toLowerCase()} visit may include:`,
      processCaption: "Dockside process",
      processOverlay: "How a visit moves from symptom to discharge",
      processEyebrow: "How we work",
      processTitle: (title: string) => `How a ${title.toLowerCase()} visit works`,
      areaEyebrow: "Service area",
      areaTitle: (title: string) => `${title} in Fort Lauderdale & South Florida`,
      areaP1: (title: string) =>
        `Owners searching for ${title.toLowerCase()} near Fort Lauderdale, Dania Beach, Hollywood, Miami, and Palm Beach County book Doctor Yachts for diagnostic-first mobile and dockside work. We confirm marina access, review symptoms before arrival, and give free estimates before authorizing major parts.`,
      areaP2a: "Local pages:",
      areaP2ftl: "Fort Lauderdale boat repair",
      areaP2all: "all service areas",
      areaP3a: "Call",
      areaP3b: "request a free estimate",
      areaP3c: "book online",
      areaP3d: "Hours:",
      whoEyebrow: "Owners & captains",
      whoTitle: "Who this service is for",
      who: [
        "Recreational boat and yacht owners in South Florida",
        "Captains needing dockside diagnosis without a tow first",
        "Owners tired of parts-swapping without a clear root cause",
        "Anyone planning seasonal maintenance or a trip checklist",
        "Buyers and owners who want findings documented in plain language",
      ],
      diagnoseEyebrow: "How we work",
      diagnoseTitle: "Why diagnose first?",
      diagnoseP1:
        "Guessing parts on marine systems is expensive—especially batteries, impellers, sensors, and chargers that get replaced without fixing the real fault. Doctor Yachts charts the symptom, tests the system, and only then recommends repairs. Free estimates keep you in control of cost and timing.",
      diagnoseP2: "Read owner guides:",
      diagnoseStart: "boat won't start",
      diagnoseHeat: "overheating",
      diagnoseMobile: "mobile vs shop",
      galleryEyebrow: "Marine gallery",
      galleryTitle: (title: string) => `${title} — waterside notes`,
      galleryBody:
        "Visual atmosphere for this service: engines, docks, systems, and South Florida water. Swap in real job photos anytime for stronger local proof.",
      galleryMeta: "South Florida · salt water",
      bookEyebrow: "Book this week",
      bookTitle: (title: string) => `Book ${title.toLowerCase()} — we confirm by phone`,
      bookBody: `Mobile and dockside when access allows across Fort Lauderdale and nearby South Florida. Share marina, slip, and symptoms. We confirm during ${site.hours}.`,
      byCity: "This service by city",
      allAreas: "All service areas →",
      relatedGuides: "Related guides",
      relatedTitle: "Related marine services",
      faqTitle: (title: string) => `${title} FAQ`,
      mediaCaption: "Marine service",
    },
    forms: {
      problem: {
        title: "What's going on with the boat?",
        help: "Tap the closest match. You can add details later.",
        label: "Problem",
      },
      where: {
        title: "Where is the boat, and when works?",
        help: "Preferred window only — we'll confirm the visit by phone or text.",
        label: "Where & when",
      },
      boat: {
        title: "Quick boat details",
        help: "Type and size help us bring the right tools. Name is optional.",
        label: "Boat",
      },
      contact: {
        title: "How do we reach you?",
        help: "Phone is best for dockside work. We confirm during shop hours.",
        label: "Contact",
      },
      stepOf: (n: number, total: number) => `Step ${n} of ${total}`,
      anythingElse: "Anything else we should know?",
      optional: "(optional)",
      detailPlaceholder: "e.g. Battery is new, hear a click, sat for 5 days…",
      urgent: "This is urgent",
      urgentHint: `No-start, overheating, bilge/flood risk. For emergencies call ${site.phone}.`,
      city: "City / area *",
      marina: "Marina, slip, or dock address *",
      marinaPlaceholder: "e.g. Bahia Mar, slip B-12",
      marinaHint: "Gate code or parking tip? Add it here — saves time on arrival.",
      date: "Preferred date *",
      time: "Preferred time *",
      boatType: "Boat type *",
      length: "Approx. length",
      boatName: "Boat name",
      boatNamePlaceholder: "e.g. Sea Ya",
      yourName: "Your name *",
      fullName: "Full name",
      phone: "Phone *",
      phoneBest: "(best way to confirm)",
      email: "Email *",
      review: "Quick review",
      reviewProblem: "Problem",
      reviewWhere: "Where",
      reviewWhen: "When",
      reviewBoat: "Boat",
      submitNote: "Submitting is a request, not a locked appointment. Prefer a quote first?",
      freeEstimate: "Free estimate",
      back: "← Back",
      continue: "Continue →",
      sending: "Sending…",
      submit: "Submit request",
      received: "Request received",
      thanks: "Thanks — we got your request",
      notLocked: `Not a locked appointment yet. We confirm access and timing during shop hours (${site.hours}).`,
      confirmation: "Confirmation",
      preferredVisit: "Preferred visit",
      location: "Location",
      urgentFlag: "Urgent",
      stuck: "Stuck at the dock? Call now:",
      backHome: "Back home",
      estimateInstead: "Free estimate instead",
      pickProblem: "Pick what best describes the problem.",
      selectCity: "Select the city or area.",
      addMarina: "Add marina name, slip, or dock address.",
      pickDate: "Pick a preferred date.",
      pickTime: "Pick a time window (or Flexible).",
      selectBoat: "Select a boat type (or Other / not sure).",
      enterName: "Enter your name.",
      enterPhone: "Enter a phone number so we can confirm.",
      enterEmail: "Enter an email for the confirmation.",
      estTitle: "Request your free estimate",
      estNeed: "What we need",
      estGet: "What you get",
      estSent: "Estimate request sent",
      estThanks: "Thanks — we'll reply with next steps",
      estReply: `Expect a response during shop hours (${site.hours}). Urgent no-start? Call ${site.phone}.`,
      sendAnother: "Send another",
      bookInstead: "Book a visit instead",
      shortDesc: "Short description *",
      estPlaceholder: "e.g. Won't crank after sitting 3 days. Battery is about a year old.",
      marinaRec: "Marina / dock",
      recommended: "(recommended)",
      marinaRecPh: "Marina name, slip, or private dock",
      howSoon: "How soon do we need it?",
      reachYou: "How do we reach you?",
      getEstimate: "Get free estimate",
      bookOnline: "Book online",
      readySchedule: "Ready to schedule a visit?",
      addNote: "Add a short note about what's happening (a sentence is enough).",
      enterPhoneEst: "Enter a phone number so we can call back.",
      contactReceived: "Message received",
      contactThanks: "Thanks — we'll reply during shop hours.",
      contactSendAnother: "Send another",
      contactName: "Name *",
      contactEmail: "Email *",
      contactPhone: "Phone",
      contactMessage: "Message *",
      contactSend: "Send message",
      sendFailed: "We couldn't deliver your message.",
      callShop: `Call ${site.phone}`,
    },
  },
  es: {
    nav: {
      home: "Inicio",
      services: "Servicios",
      areas: "Zonas",
      guides: "Guías",
      faq: "Preguntas",
      about: "Nosotros",
      contact: "Contacto",
      book: "Reservar",
      bookVisit: "Reservar visita",
      call: "Llamar",
      menu: "Menú",
      close: "Cerrar",
      mainNav: "Principal",
      mobileNav: "Móvil",
      language: "Idioma",
    },
    footer: {
      blurb:
        "Diagnóstico y reparación náutica independiente. Hallazgos claros, presupuestos gratis, en el muelle cuando el acceso lo permite.",
      services: "Servicios",
      areas: "Zonas",
      book: "Reservar",
      bookVisit: "Reservar visita",
      estimate: "Pedir presupuesto gratis",
      reviews: "Reseñas",
      privacy: "Privacidad",
      terms: "Términos",
      tag: "Primero diagnosticamos · presupuestos gratis",
    },
    cta: {
      eyebrow: "Reserve esta semana",
      title: "Reserve una visita — confirmamos por teléfono",
      body: `Envíe la solicitud o llame al ${site.phone}. Confirmamos en horario ${site.hoursEs}. Primero diagnosticamos. Presupuesto gratis del trabajo recomendado.`,
      reviews: "Reseñas en",
      book: "Reservar visita",
      estimate: "Pedir presupuesto gratis",
      call: `Llamar ${site.phone}`,
    },
    mobileCta: {
      call: "Llamar",
      estimate: "Presupuesto",
      book: "Reservar visita",
    },
    serviceCard: {
      details: "Ver el servicio →",
    },
    servicePage: {
      eyebrow: (duration?: string) => (duration ? `Servicio · ${duration}` : "Servicio"),
      crumbHome: "Inicio",
      crumbServices: "Servicios",
      areaLine: "Fort Lauderdale · el sur de la Florida · primero en el muelle",
      book: "Reservar visita",
      estimate: "Pedir presupuesto gratis",
      call: `Llamar ${site.phone}`,
      quickLabel: "Respuesta rápida · en el agua",
      quickQuestion: (title: string) => `¿Qué es ${title.toLowerCase()}?`,
      aboutEyebrow: "En el muelle",
      aboutTitle: (title: string) => `${title} en Doctor Yachts`,
      symptomsEyebrow: "Síntomas",
      symptomsTitle: "Síntomas que vemos a menudo",
      symptomsLead: "Si algo de esto le suena, este suele ser el servicio correcto para empezar:",
      scopeEyebrow: "Alcance",
      scopeTitle: "Qué suele incluir",
      detailsEyebrow: "Detalle",
      inspectEyebrow: "Inspección",
      inspectTitle: "Qué revisamos en la visita",
      inspectLead: (title: string) =>
        `El alcance sigue su síntoma y su embarcación, pero una visita típica de ${title.toLowerCase()} puede incluir:`,
      processCaption: "Proceso en el muelle",
      processOverlay: "De síntoma a alta, con un plan",
      processEyebrow: "Cómo trabajamos",
      processTitle: (title: string) => `Cómo es una visita de ${title.toLowerCase()}`,
      areaEyebrow: "Zona de servicio",
      areaTitle: (title: string) => `${title} en Fort Lauderdale y el sur de la Florida`,
      areaP1: (title: string) =>
        `Dueños que buscan ${title.toLowerCase()} cerca de Fort Lauderdale, Dania Beach, Hollywood, Miami y el condado de Palm Beach reservan Doctor Yachts para trabajo móvil y en el muelle, con diagnóstico primero. Confirmamos el acceso a la marina, repasamos los síntomas antes de llegar y damos presupuesto gratis antes de autorizar piezas mayores.`,
      areaP2a: "Páginas locales:",
      areaP2ftl: "reparación de barcos en Fort Lauderdale",
      areaP2all: "todas las zonas",
      areaP3a: "Llame al",
      areaP3b: "pida un presupuesto gratis",
      areaP3c: "reserve en línea",
      areaP3d: "Horario:",
      whoEyebrow: "Dueños y capitanes",
      whoTitle: "Para quién es este servicio",
      who: [
        "Dueños de botes y yates de recreo en el sur de la Florida",
        "Capitanes que necesitan diagnóstico en el muelle, sin remolque primero",
        "Dueños cansados de cambiar piezas sin una causa clara",
        "Quien planea mantenimiento de temporada o una lista antes de un viaje",
        "Compradores y dueños que quieren hallazgos por escrito, en lenguaje claro",
      ],
      diagnoseEyebrow: "Cómo trabajamos",
      diagnoseTitle: "¿Por qué diagnosticar primero?",
      diagnoseP1:
        "Adivinar piezas en sistemas marinos sale caro—sobre todo baterías, impulsores, sensores y cargadores que se cambian sin resolver la falla. Doctor Yachts sigue el síntoma, prueba el sistema y recién entonces recomienda la reparación. El presupuesto gratis le deja el control del costo y del momento.",
      diagnoseP2: "Lea las guías:",
      diagnoseStart: "el bote no arranca",
      diagnoseHeat: "sobrecalentamiento",
      diagnoseMobile: "móvil vs taller",
      galleryEyebrow: "Galería náutica",
      galleryTitle: (title: string) => `${title} — notas a orilla de agua`,
      galleryBody:
        "Ambiente visual de este servicio: motores, muelles, sistemas y el agua del sur de la Florida. Puede cambiarse por fotos reales del trabajo cuando las tenga.",
      galleryMeta: "El sur de la Florida · agua salada",
      bookEyebrow: "Reserve esta semana",
      bookTitle: (title: string) => `Reserve ${title.toLowerCase()} — confirmamos por teléfono`,
      bookBody: `Móvil y en el muelle cuando el acceso lo permite en Fort Lauderdale y el sur de la Florida. Indique marina, slip y síntomas. Confirmamos en horario ${site.hoursEs}.`,
      byCity: "Este servicio por ciudad",
      allAreas: "Todas las zonas →",
      relatedGuides: "Guías relacionadas",
      relatedTitle: "Otros servicios náuticos",
      faqTitle: (title: string) => `Preguntas de ${title}`,
      mediaCaption: "Servicio náutico",
    },
    forms: {
      problem: {
        title: "¿Qué le pasa al bote?",
        help: "Toque lo que más se acerque. Puede agregar detalles después.",
        label: "Problema",
      },
      where: {
        title: "¿Dónde está el bote y cuándo le sirve?",
        help: "Es una ventana preferida — confirmamos la visita por teléfono o texto.",
        label: "Dónde y cuándo",
      },
      boat: {
        title: "Datos rápidos del bote",
        help: "El tipo y el tamaño nos ayudan a llevar las herramientas correctas. El nombre es opcional.",
        label: "Bote",
      },
      contact: {
        title: "¿Cómo lo localizamos?",
        help: "El teléfono es lo mejor para trabajo en el muelle. Confirmamos en horario del taller.",
        label: "Contacto",
      },
      stepOf: (n: number, total: number) => `Paso ${n} de ${total}`,
      anythingElse: "¿Algo más que debamos saber?",
      optional: "(opcional)",
      detailPlaceholder: "Ej. La batería es nueva, se oye un click, estuvo 5 días parado…",
      urgent: "Esto es urgente",
      urgentHint: `No arranca, se calienta o hay riesgo de sentina. En emergencia llame al ${site.phone}.`,
      city: "Ciudad / zona *",
      marina: "Marina, slip o dirección del muelle *",
      marinaPlaceholder: "Ej. Bahia Mar, slip B-12",
      marinaHint: "¿Código de portón o tip de parqueo? Agréguelo aquí — ahorra tiempo al llegar.",
      date: "Fecha preferida *",
      time: "Hora preferida *",
      boatType: "Tipo de bote *",
      length: "Eslora aproximada",
      boatName: "Nombre del bote",
      boatNamePlaceholder: "Ej. Sea Ya",
      yourName: "Su nombre *",
      fullName: "Nombre completo",
      phone: "Teléfono *",
      phoneBest: "(la mejor forma de confirmar)",
      email: "Correo *",
      review: "Repaso rápido",
      reviewProblem: "Problema",
      reviewWhere: "Dónde",
      reviewWhen: "Cuándo",
      reviewBoat: "Bote",
      submitNote: "Enviar es una solicitud, no una cita bloqueada. ¿Prefiere cotizar primero?",
      freeEstimate: "Presupuesto gratis",
      back: "← Atrás",
      continue: "Continuar →",
      sending: "Enviando…",
      submit: "Enviar solicitud",
      received: "Solicitud recibida",
      thanks: "Gracias — recibimos su solicitud",
      notLocked: `Todavía no es una cita fija. Confirmamos acceso y horario en horas del taller (${site.hoursEs}).`,
      confirmation: "Confirmación",
      preferredVisit: "Visita preferida",
      location: "Ubicación",
      urgentFlag: "Urgente",
      stuck: "¿Quedó en el muelle? Llame ahora:",
      backHome: "Volver al inicio",
      estimateInstead: "Pedir presupuesto",
      pickProblem: "Elija lo que mejor describe el problema.",
      selectCity: "Seleccione la ciudad o zona.",
      addMarina: "Agregue marina, slip o dirección del muelle.",
      pickDate: "Elija una fecha preferida.",
      pickTime: "Elija una ventana de hora (o Flexible).",
      selectBoat: "Seleccione el tipo de bote (u Otro / no sé).",
      enterName: "Escriba su nombre.",
      enterPhone: "Escriba un teléfono para confirmar.",
      enterEmail: "Escriba un correo para la confirmación.",
      estTitle: "Pida su presupuesto gratis",
      estNeed: "Qué necesitamos",
      estGet: "Qué recibe",
      estSent: "Solicitud de presupuesto enviada",
      estThanks: "Gracias — le respondemos con los siguientes pasos",
      estReply: `Respondemos en horario del taller (${site.hoursEs}). ¿No arranca y es urgente? Llame al ${site.phone}.`,
      sendAnother: "Enviar otra",
      bookInstead: "Reservar visita",
      shortDesc: "Descripción corta *",
      estPlaceholder: "Ej. No da arranque después de 3 días parado. La batería tiene como un año.",
      marinaRec: "Marina / muelle",
      recommended: "(recomendado)",
      marinaRecPh: "Nombre de la marina, slip o muelle privado",
      howSoon: "¿Para cuándo lo necesita?",
      reachYou: "¿Cómo lo localizamos?",
      getEstimate: "Pedir presupuesto gratis",
      bookOnline: "Reservar en línea",
      readySchedule: "¿Listo para agendar la visita?",
      addNote: "Agregue una nota corta de lo que está pasando (una frase basta).",
      enterPhoneEst: "Escriba un teléfono para devolverle la llamada.",
      contactReceived: "Mensaje recibido",
      contactThanks: "Gracias — respondemos en horario del taller.",
      contactSendAnother: "Enviar otro",
      contactName: "Nombre *",
      contactEmail: "Correo *",
      contactPhone: "Teléfono",
      contactMessage: "Mensaje *",
      contactSend: "Enviar mensaje",
      sendFailed: "No pudimos entregar su mensaje.",
      callShop: `Llamar ${site.phone}`,
    },
  },
} as const;

export function t(locale: Locale) {
  return chrome[locale];
}
